apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  MYSQL_HOST: {{ .Values.config.mysqlHost | quote }}
  MYSQL_USER: {{ .Values.config.mysqlUser | quote }}
  MYSQL_DB: {{ .Values.config.mysqlDb | quote }}
