apiVersion: v1
kind: Service
metadata:
  name: secret-santa-service
  labels:
    app: secret-santa
spec:
  type: NodePort

  selector:
    app: secret-santa

  ports:
    - protocol: TCP
      port: 5000        # Service port (inside cluster)
      targetPort: 5000  # Container port
      nodePort: 30080   # External access port (30000–32767)
